name: prompt_result
description: "Тестовое задание (Flutter, до 4 часов). Создать Flutter-приложение из 2 экранов Prompt → Result"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Основные зависимости Flutter
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Управление состоянием
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  equatable: ^2.0.7

  # Навигация
  go_router: ^16.2.4

  # Внедрение зависимостей
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Мультимедиа и UI компоненты
  lottie: ^3.3.2

# Инструменты разработки
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Генерация кода и DI
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0
  
  # Иконки и локализация
  flutter_launcher_icons: ^0.14.4
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/lottie/

flutter_intl:
  enabled: true
  class_name: Locales

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/app_icon.png"