name: prompt_result
description: "Тестовое задание (Flutter, до 4 часов). Создать Flutter-приложение из 2 экранов Prompt → Result"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  get_it: ^8.2.0
  injectable: ^2.5.2
  intl: ^0.20.2
  intl_utils: ^2.8.7
  go_router: ^16.2.4
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/vectors/

flutter_intl:
  enabled: true
  class_name: Locales

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/app_icon.png"
